export type Product = { id:string; name:string; category:string; price:number; oldPrice?:number; rating:number; reviews:number; image:string; description:string; badge?:string };
export const products: Product[] = [
 {id:'nova-earbuds',name:'Nova Wireless Noise-Cancelling Earbuds',category:'Electronics',price:39.99,oldPrice:59.99,rating:4.7,reviews:218,image:'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=700&q=85',description:'Immersive sound with a compact charging case, clear calls, and up to 28 hours of listening.',badge:'-33%'},
 {id:'urban-sneakers',name:'Urban Run Everyday Sneakers',category:'Fashion',price:44.50,oldPrice:65,rating:4.5,reviews:89,image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=85',description:'Comfortable, lightweight sneakers made for commutes, errands, and weekends.',badge:'-32%'},
 {id:'glow-serum',name:'Glow & Co. Vitamin C Face Serum',category:'Beauty',price:16.99,oldPrice:24.99,rating:4.8,reviews:431,image:'https://images.unsplash.com/photo-1570194065650-d99fb4bedf0e?auto=format&fit=crop&w=700&q=85',description:'A brightening daily serum with vitamin C and hyaluronic acid for a healthy-looking glow.',badge:'-32%'},
 {id:'coffee-maker',name:'BrewHouse Compact Coffee Maker',category:'Home & Living',price:52,oldPrice:79,rating:4.6,reviews:144,image:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=700&q=85',description:'A simple, space-saving coffee maker that delivers a rich cup in minutes.',badge:'-34%'},
 {id:'smart-watch',name:'Pulse Smart Watch with Health Tracking',category:'Electronics',price:69.99,oldPrice:99.99,rating:4.4,reviews:76,image:'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=700&q=85',description:'Stay connected and keep an eye on your activity, sleep, heart rate, and more.',badge:'-30%'},
 {id:'woven-basket',name:'Handwoven Storage Basket Set',category:'Home & Living',price:28,oldPrice:36,rating:4.9,reviews:58,image:'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=700&q=85',description:'Warm, durable woven baskets that make everyday organization look effortless.',badge:'-22%'},
 {id:'kids-blocks',name:'Creative Builder Blocks, 120 Pieces',category:'Kids & Toys',price:21.5,oldPrice:29.5,rating:4.7,reviews:192,image:'https://images.unsplash.com/photo-1599623560574-39d485900c95?auto=format&fit=crop&w=700&q=85',description:'Colorful building blocks that invite hours of open-ended, imaginative play.',badge:'-27%'},
 {id:'snack-box',name:'Better Bites Healthy Snack Variety Box',category:'Groceries',price:18.99,rating:4.3,reviews:42,image:'https://images.unsplash.com/photo-1621939514649-280e2aa2d0c8?auto=format&fit=crop&w=700&q=85',description:'A cheerful mix of delicious, better-for-you snacks for work, travel, and home.'}
];
export const categories=[...new Set(products.map(p=>p.category))];
export const getProduct=(id:string)=>products.find((p)=>p.id===id);
